[package]
name = "tds_encoding"
version = "0.1.0"
authors = []

[lib]
name = "tds_encoding"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.1"
rustler_codegen = "0.22.0-rc.1"
lazy_static = "1.4"
encoding = "0.2.33"